### ISSUE TITLE
bug: Buttons have Focusable mode on Issue

### ISSUE THREAD

**Issue by EhsanulHaqueSiam** [EhsanulHaqueSiam/HotelManagementSystem#18]
### Type

Cosmetic

### Bug description

Button Set Focusable OFF

### Steps to reproduce

All buttons have focusable mode on 

### Relevant log output

```shell
Not available at the Moment
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by NitPaul** [comment]
This issue have been fixed
